import { parseXML } from '../server/src/lib/xml-parser';
import { mapTahsilatXmlToBulkRequest } from '../server/src/lib/mappers/tahsilat-mapper';

const sampleXML = `
<?xml version="1.0" encoding="utf-8"?><TAHSILATLAR><TAHSILAT> <LNGDISTKOD>903</LNGDISTKOD> <LNGYIL>2026</LNGYIL> <LNGKOD>1303079</LNGKOD> <BYTTIP>0</BYTTIP> <LNGISLEMTIP>0</LNGISLEMTIP> <BYTACIKKAPALI>0</BYTACIKKAPALI> <LNGMUSTERIKOD>0</LNGMUSTERIKOD> <TXTMUSTERIKOD>08412</TXTMUSTERIKOD> <TXTSTKOD>715</TXTSTKOD> <LNGSTKOD>715</LNGSTKOD> <LNGTAHSILATSTKOD>0</LNGTAHSILATSTKOD> <TXTMAKBUZNO>50656</TXTMAKBUZNO> <TXTBELGENO /> <TXTACIKLAMA>1248989</TXTACIKLAMA> <DBLTUTAR>21248.960000</DBLTUTAR> <BYTBAKIYEKOD>2</BYTBAKIYEKOD> <BYTGIRISTIP>6</BYTGIRISTIP> <BYTBASIMDURUM>0</BYTBASIMDURUM> <BYTDURUM>1</BYTDURUM> <BYTODENDI>1</BYTODENDI> <TXTBANKA>0001</TXTBANKA> <TXTBANKASUBE /> <TXTESASBORCLU /> <TXTKESIDEYERI /> <TXTCEKNO></TXTCEKNO> <TXTKARTNO /> <TRHSONISLEMTARIHI>14-01-2026 00:00:00</TRHSONISLEMTARIHI> <LNGSONKULLANICIKOD>0</LNGSONKULLANICIKOD> <TRHILKISLEMTARIHI>14-01-2026 00:00:00</TRHILKISLEMTARIHI> <LNGILKKULLANICIKOD>0</LNGILKKULLANICIKOD> <TXTREFERANS /> <LNGFATURAKOD /> <TXTHESAPNO /> <DBLBELGEDOVIZKUR /> <TXTBELGEPARABIRIMI /> <TRHISLEMTARIHI>14-01-2026 00:00:00</TRHISLEMTARIHI> <TRHVADETARIHI>14-01-2026 00:00:00</TRHVADETARIHI> <TRHODEMETARIHI>14-01-2026 00:00:00</TRHODEMETARIHI> </TAHSILAT></TAHSILATLAR>
`;

try {
    console.log("Parsing XML...");
    const parsed = parseXML(sampleXML);
    console.log("XML Parsed. Mapping to JSON...");
    const payload = mapTahsilatXmlToBulkRequest(parsed);
    console.log("Mapped Payload:");
    console.log(JSON.stringify(payload, null, 2));
} catch (error) {
    console.error("Error:", error);
}
